### ISSUE TITLE
possible break in functionality after code update

### ISSUE THREAD

**Issue by jalajc** [jeffmeloy/py2dataset#16]
1. not sure if the logic here is intentional because it doesn't match the comment above the code. So though to check with you, I feel something amiss... https://github.com/jeffmeloy/py2dataset/blob/b1dcdd92336bf5ec381897dae9a59efc287415c0/py2dataset.py#L159

also, 
2. if you can check https://github.com/jeffmeloy/py2dataset/blob/b1dcdd92336bf5ec381897dae9a59efc287415c0/py2dataset.py#L85 in light of later used expression at  https://github.com/jeffmeloy/py2dataset/blob/b1dcdd92336bf5ec381897dae9a59efc287415c0/py2dataset.py#L152
  ```python
  if not use_llm:
      single_process = True
  ```

**Comment by jeffmeloy** [comment]
Thanks for comment. I realized this was confusing and maybe wrong, I've updated the logic and the comments in the latest version.
