### ISSUE TITLE
The new code base blows up the context window with input

### ISSUE THREAD

**Issue by cmosguy** [jeffmeloy/py2dataset#9]
Hey @jeffmeloy  I get OOM with the new code:

```python
def get_response_from_llm(self, query: str, context: str) -> str:
        """
        Get language model response to query for given context.
        Args:
            query (str): The query to be used for generating the response.
            context (str): The context to be used for generating the response.
        Returns:
            str: The generated response.
        """
        # Update the context with the selected instructions from the instruct_list
        excluded_instructions = ["What is the call code graph", "What is the docstring"]
        filtered_instruct_list = [
            item
            for item in self.instruct_list
            if not any(
                item["instruction"].startswith(prefix)
                for prefix in excluded_instructions
            )
        ]
        past_instructs = "\n".join(
            [
                f"Instruction: {item['instruction']} \nOutput: {item['output']}"
                for item in filtered_instruct_list
            ]
        )
        full_context = (
            context
            + "\n"
            + "Here's some detail about this code:"
            + "\n"
            + past_instructs
        )
```

It blows up the context window and creates OOM for the input of the LLM.

**Comment by jeffmeloy** [comment]
the new version adds additional context from the AST, which helps the LLM give better answers, but does require more memory. Can you try this making this change to see if this helps?  If so, I can add a command line arg to prevent adding context.

NEW version:
def get_response_from_llm(self, query: str, context: str) -> str:
        """
        Get language model response to query for given context.
        Args:
            query (str): The query to be used for generating the response.
            context (str): The context to be used for generating the response.
        Returns:
            str: The generated response.
        """
                
        try:
            prompt = self.prompt.format(context=context, query=query)
            logging.info(f'Query: {query}')
            response = self.llm(prompt)
            response = re.sub(r'\n\s*\n', '\n\n', response) # remove extra newlines
            logging.info(f'Response: {response}')
        except:
            logger.error('Failed to generate model response')
        return response

**Comment by jeffmeloy** [comment]
The context being added should not be that much, but I've cranked up the context window based on the HW I'm using to be able to process larger Python code files....this is the most likely problem. 

Recommend primary change needed will be to adjust the py2dataset_model_config.yaml parameters to work with your HW and model/model size.

**Comment by cmosguy** [comment]
Thanks @jeffmeloy,

Yes, I do not know what to say, I am just ingesting python code base as you would in your example of this repo.

In the code above I think you want to have:

```python
    try:
        prompt = self.prompt.format(context=context, query=query)
        logging.info(f'Query: {query}')
        prompt = re.sub(r'\n\s*\n', '\n\n', prompt) # <--remove extra newlines in prompt
        response = self.llm(prompt)
        logging.info(f'Response: {response}')
    except:
        logger.error('Failed to generate model response')
    return response
```

I have this in my YAML:
```yaml
  model_params:
    ## USABLE OUTPUT WITH CURRENT PROMPT TEMPLATE
    model_path: "TheBloke/WizardCoder-Python-13B-V1.0-GGUF"
    model_file: "wizardcoder-python-13b-v1.0.Q5_K_S.gguf"
    model_type: "llama"
    batch_size: 256
    threads: 28
    context_length: 8400
    max_new_tokens: 8092
    gpu_layers: 100
    reset: true
```
I am trying to use CUDA but it still yields this warning even when I trim things down:
```
2023-10-04 09:02:22,175 - WARNING - Number of tokens (35928) exceeded maximum context length (8400).
```


I did try just using the prompt without the `past_instructs` but it still seems way too much for some reason.

Thoughts?

**Comment by jeffmeloy** [comment]
What is the file size you are trying to use?

**Comment by cmosguy** [comment]
hey @jeffmeloy !

The file size ranges to be `60942` to `221321`.

**Comment by jeffmeloy** [comment]
Got it.....the large file size is reason for you're error. I've done some
experiments to define some chunking to allow LLm to process large code
files like this and then put it all back together. Give me a few days.

I wanted to add some code from here into my datasets anyway but the files
were too large, this give me a good excuse to work on it:
https://github.com/python-control/python-control.

**Comment by cmosguy** [comment]
@jeffmeloy - ok this looks quite interesting project.

BTW, I am looking at this code base to figure out how to do FIM to build fine tuning for code infilling:

https://github.com/microsoft/CodeT/tree/main/RepoCoder

And this starcoder example has some interesting nuggets for generating FIM on existing code:

https://github.com/loubnabnl/santacoder-finetuning

those 🤗 are smart people.

**Comment by jeffmeloy** [comment]
I've created an update that determines the context and then iterativly uses smaller and smaller context for the LLM. In sequence:
1. full source code + the questions and answers about the code 
2. source code with all comments and docstrings removed + the questions and answers about the code
3. the function, class, method definitions, calls, and returns + the questions and answers about the code
4. the questions and answers about the code
If context still too long then give up, output a warning about required context_length in the py2dataset_model_config.yaml and go on to the next file.
